### ISSUE TITLE
kebabCase can return invalid branch names

### ISSUE THREAD

**Issue by brennanmceachran** [mirrajabi/aider-github-workflows#4]
Great action, had an error i figured was worth reporting.

Looks like [this line](https://github.com/mirrajabi/aider-github-workflows/blob/3d61fab0ffeee8c58d9abc0915089408ba572415/.github/workflows/aider-issue-to-pr.yml#L64) can return invalid branch names causing the workflow to fail.
```ts
const kebabCase = (str) => str.toLowerCase().replace(/\s+/g, '-');
```

I *think* a better function would be
```ts
const kebabCase = (str) => {
    return str
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, '') // Remove invalid characters
        .replace(/\s+/g, '-')     // Replace spaces with dashes
        .replace(/^-+|-+$/g, ''); // Remove leading/trailing dashes
};
```

**Comment by mirrajabi** [comment]
Thanks @brennanmceachran for reporting and providing the fix!
